// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: TeledonProtocol_v3.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Proto.ProtoBuffProtocol {

  /// <summary>Holder for reflection information generated from TeledonProtocol_v3.proto</summary>
  public static partial class TeledonProtocolV3Reflection {

    #region Descriptor
    /// <summary>File descriptor for TeledonProtocol_v3.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TeledonProtocolV3Reflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChhUZWxlZG9uUHJvdG9jb2xfdjMucHJvdG8SF3Byb3RvLnByb3RvQnVmZlBy",
            "b3RvY29sIjgKCVZvbHVudGVlchINCgVlbWFpbBgBIAEoCRIQCghwYXNzd29y",
            "ZBgCIAEoCRIKCgJpZBgDIAEoAyKAAQoIRG9uYXRpb24SDgoGaWRDYXNlGAEg",
            "ASgJEhYKDmRvbm9yRmlyc3ROYW1lGAIgASgJEhUKDWRvbm9yTGFzdE5hbWUY",
            "AyABKAkSDwoHYWRkcmVzcxgEIAEoCRINCgVwaG9uZRgFIAEoCRIVCg1hbW91",
            "bnREb25hdGVkGAYgASgJIkAKC0NoYXJpdHlDYXNlEhAKCGNhc2VOYW1lGAEg",
            "ASgJEhMKC3RvdGFsQW1vdW50GAIgASgCEgoKAmlkGAMgASgDIrwCCg5UZWxl",
            "ZG9uUmVxdWVzdBI6CgR0eXBlGAEgASgOMiwucHJvdG8ucHJvdG9CdWZmUHJv",
            "dG9jb2wuVGVsZWRvblJlcXVlc3QuVHlwZRIyCgR1c2VyGAIgASgLMiIucHJv",
            "dG8ucHJvdG9CdWZmUHJvdG9jb2wuVm9sdW50ZWVySAASFAoKc2VhcmNoTmFt",
            "ZRgDIAEoCUgAEjUKCGRvbmF0aW9uGAUgASgLMiEucHJvdG8ucHJvdG9CdWZm",
            "UHJvdG9jb2wuRG9uYXRpb25IACJiCgRUeXBlEgsKB1Vua25vd24QABIJCgVM",
            "b2dpbhABEgoKBkxvZ291dBACEhAKDEdldERvbmF0aW9ucxADEhMKD0dldENo",
            "YXJpdHlDYXNlcxAEEg8KC0FkZERvbmF0aW9uEAVCCQoHcGF5bG9hZCKkAwoP",
            "VGVsZWRvblJlc3BvbnNlEjsKBHR5cGUYASABKA4yLS5wcm90by5wcm90b0J1",
            "ZmZQcm90b2NvbC5UZWxlZG9uUmVzcG9uc2UuVHlwZRINCgVlcnJvchgCIAEo",
            "CRI0Cglkb25hdGlvbnMYAyADKAsyIS5wcm90by5wcm90b0J1ZmZQcm90b2Nv",
            "bC5Eb25hdGlvbhIzCgVjYXNlcxgEIAMoCzIkLnByb3RvLnByb3RvQnVmZlBy",
            "b3RvY29sLkNoYXJpdHlDYXNlEjQKBmNhc2VzMhgGIAMoCzIkLnByb3RvLnBy",
            "b3RvQnVmZlByb3RvY29sLkNoYXJpdHlDYXNlEjMKCGRvbmF0aW9uGAUgASgL",
            "MiEucHJvdG8ucHJvdG9CdWZmUHJvdG9jb2wuRG9uYXRpb24ibwoEVHlwZRIL",
            "CgdVbmtub3duEAASBgoCT2sQARIJCgVFcnJvchACEhAKDEdldERvbmF0aW9u",
            "cxADEhMKD0dldENoYXJpdHlDYXNlcxAEEg8KC05ld0RvbmF0aW9uEAUSDwoL",
            "VXBkYXRlQ2FzZXMQBkIdChFwcm90b0J1ZmZQcm90b2NvbEIITGFiNF9NUFBi",
            "BnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Proto.ProtoBuffProtocol.Volunteer), global::Proto.ProtoBuffProtocol.Volunteer.Parser, new[]{ "Email", "Password", "Id" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Proto.ProtoBuffProtocol.Donation), global::Proto.ProtoBuffProtocol.Donation.Parser, new[]{ "IdCase", "DonorFirstName", "DonorLastName", "Address", "Phone", "AmountDonated" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Proto.ProtoBuffProtocol.CharityCase), global::Proto.ProtoBuffProtocol.CharityCase.Parser, new[]{ "CaseName", "TotalAmount", "Id" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Proto.ProtoBuffProtocol.TeledonRequest), global::Proto.ProtoBuffProtocol.TeledonRequest.Parser, new[]{ "Type", "User", "SearchName", "Donation" }, new[]{ "Payload" }, new[]{ typeof(global::Proto.ProtoBuffProtocol.TeledonRequest.Types.Type) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Proto.ProtoBuffProtocol.TeledonResponse), global::Proto.ProtoBuffProtocol.TeledonResponse.Parser, new[]{ "Type", "Error", "Donations", "Cases", "Cases2", "Donation" }, null, new[]{ typeof(global::Proto.ProtoBuffProtocol.TeledonResponse.Types.Type) }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Volunteer : pb::IMessage<Volunteer>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Volunteer> _parser = new pb::MessageParser<Volunteer>(() => new Volunteer());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Volunteer> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Proto.ProtoBuffProtocol.TeledonProtocolV3Reflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Volunteer() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Volunteer(Volunteer other) : this() {
      email_ = other.email_;
      password_ = other.password_;
      id_ = other.id_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Volunteer Clone() {
      return new Volunteer(this);
    }

    /// <summary>Field number for the "email" field.</summary>
    public const int EmailFieldNumber = 1;
    private string email_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Email {
      get { return email_; }
      set {
        email_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "password" field.</summary>
    public const int PasswordFieldNumber = 2;
    private string password_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Password {
      get { return password_; }
      set {
        password_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 3;
    private long id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Volunteer);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Volunteer other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Email != other.Email) return false;
      if (Password != other.Password) return false;
      if (Id != other.Id) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Email.Length != 0) hash ^= Email.GetHashCode();
      if (Password.Length != 0) hash ^= Password.GetHashCode();
      if (Id != 0L) hash ^= Id.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Email.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Email);
      }
      if (Password.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Password);
      }
      if (Id != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(Id);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Email.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Email);
      }
      if (Password.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Password);
      }
      if (Id != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(Id);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Email.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Email);
      }
      if (Password.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Password);
      }
      if (Id != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Id);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Volunteer other) {
      if (other == null) {
        return;
      }
      if (other.Email.Length != 0) {
        Email = other.Email;
      }
      if (other.Password.Length != 0) {
        Password = other.Password;
      }
      if (other.Id != 0L) {
        Id = other.Id;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Email = input.ReadString();
            break;
          }
          case 18: {
            Password = input.ReadString();
            break;
          }
          case 24: {
            Id = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Email = input.ReadString();
            break;
          }
          case 18: {
            Password = input.ReadString();
            break;
          }
          case 24: {
            Id = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class Donation : pb::IMessage<Donation>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Donation> _parser = new pb::MessageParser<Donation>(() => new Donation());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Donation> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Proto.ProtoBuffProtocol.TeledonProtocolV3Reflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Donation() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Donation(Donation other) : this() {
      idCase_ = other.idCase_;
      donorFirstName_ = other.donorFirstName_;
      donorLastName_ = other.donorLastName_;
      address_ = other.address_;
      phone_ = other.phone_;
      amountDonated_ = other.amountDonated_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Donation Clone() {
      return new Donation(this);
    }

    /// <summary>Field number for the "idCase" field.</summary>
    public const int IdCaseFieldNumber = 1;
    private string idCase_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string IdCase {
      get { return idCase_; }
      set {
        idCase_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "donorFirstName" field.</summary>
    public const int DonorFirstNameFieldNumber = 2;
    private string donorFirstName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string DonorFirstName {
      get { return donorFirstName_; }
      set {
        donorFirstName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "donorLastName" field.</summary>
    public const int DonorLastNameFieldNumber = 3;
    private string donorLastName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string DonorLastName {
      get { return donorLastName_; }
      set {
        donorLastName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "address" field.</summary>
    public const int AddressFieldNumber = 4;
    private string address_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Address {
      get { return address_; }
      set {
        address_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "phone" field.</summary>
    public const int PhoneFieldNumber = 5;
    private string phone_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Phone {
      get { return phone_; }
      set {
        phone_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "amountDonated" field.</summary>
    public const int AmountDonatedFieldNumber = 6;
    private string amountDonated_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string AmountDonated {
      get { return amountDonated_; }
      set {
        amountDonated_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Donation);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Donation other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (IdCase != other.IdCase) return false;
      if (DonorFirstName != other.DonorFirstName) return false;
      if (DonorLastName != other.DonorLastName) return false;
      if (Address != other.Address) return false;
      if (Phone != other.Phone) return false;
      if (AmountDonated != other.AmountDonated) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (IdCase.Length != 0) hash ^= IdCase.GetHashCode();
      if (DonorFirstName.Length != 0) hash ^= DonorFirstName.GetHashCode();
      if (DonorLastName.Length != 0) hash ^= DonorLastName.GetHashCode();
      if (Address.Length != 0) hash ^= Address.GetHashCode();
      if (Phone.Length != 0) hash ^= Phone.GetHashCode();
      if (AmountDonated.Length != 0) hash ^= AmountDonated.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (IdCase.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(IdCase);
      }
      if (DonorFirstName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(DonorFirstName);
      }
      if (DonorLastName.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(DonorLastName);
      }
      if (Address.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Address);
      }
      if (Phone.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Phone);
      }
      if (AmountDonated.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(AmountDonated);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (IdCase.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(IdCase);
      }
      if (DonorFirstName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(DonorFirstName);
      }
      if (DonorLastName.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(DonorLastName);
      }
      if (Address.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Address);
      }
      if (Phone.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Phone);
      }
      if (AmountDonated.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(AmountDonated);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (IdCase.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(IdCase);
      }
      if (DonorFirstName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DonorFirstName);
      }
      if (DonorLastName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DonorLastName);
      }
      if (Address.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Address);
      }
      if (Phone.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Phone);
      }
      if (AmountDonated.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AmountDonated);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Donation other) {
      if (other == null) {
        return;
      }
      if (other.IdCase.Length != 0) {
        IdCase = other.IdCase;
      }
      if (other.DonorFirstName.Length != 0) {
        DonorFirstName = other.DonorFirstName;
      }
      if (other.DonorLastName.Length != 0) {
        DonorLastName = other.DonorLastName;
      }
      if (other.Address.Length != 0) {
        Address = other.Address;
      }
      if (other.Phone.Length != 0) {
        Phone = other.Phone;
      }
      if (other.AmountDonated.Length != 0) {
        AmountDonated = other.AmountDonated;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            IdCase = input.ReadString();
            break;
          }
          case 18: {
            DonorFirstName = input.ReadString();
            break;
          }
          case 26: {
            DonorLastName = input.ReadString();
            break;
          }
          case 34: {
            Address = input.ReadString();
            break;
          }
          case 42: {
            Phone = input.ReadString();
            break;
          }
          case 50: {
            AmountDonated = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            IdCase = input.ReadString();
            break;
          }
          case 18: {
            DonorFirstName = input.ReadString();
            break;
          }
          case 26: {
            DonorLastName = input.ReadString();
            break;
          }
          case 34: {
            Address = input.ReadString();
            break;
          }
          case 42: {
            Phone = input.ReadString();
            break;
          }
          case 50: {
            AmountDonated = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class CharityCase : pb::IMessage<CharityCase>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CharityCase> _parser = new pb::MessageParser<CharityCase>(() => new CharityCase());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CharityCase> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Proto.ProtoBuffProtocol.TeledonProtocolV3Reflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CharityCase() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CharityCase(CharityCase other) : this() {
      caseName_ = other.caseName_;
      totalAmount_ = other.totalAmount_;
      id_ = other.id_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CharityCase Clone() {
      return new CharityCase(this);
    }

    /// <summary>Field number for the "caseName" field.</summary>
    public const int CaseNameFieldNumber = 1;
    private string caseName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string CaseName {
      get { return caseName_; }
      set {
        caseName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "totalAmount" field.</summary>
    public const int TotalAmountFieldNumber = 2;
    private float totalAmount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float TotalAmount {
      get { return totalAmount_; }
      set {
        totalAmount_ = value;
      }
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 3;
    private long id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CharityCase);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CharityCase other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (CaseName != other.CaseName) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(TotalAmount, other.TotalAmount)) return false;
      if (Id != other.Id) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (CaseName.Length != 0) hash ^= CaseName.GetHashCode();
      if (TotalAmount != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(TotalAmount);
      if (Id != 0L) hash ^= Id.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (CaseName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(CaseName);
      }
      if (TotalAmount != 0F) {
        output.WriteRawTag(21);
        output.WriteFloat(TotalAmount);
      }
      if (Id != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(Id);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (CaseName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(CaseName);
      }
      if (TotalAmount != 0F) {
        output.WriteRawTag(21);
        output.WriteFloat(TotalAmount);
      }
      if (Id != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(Id);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (CaseName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CaseName);
      }
      if (TotalAmount != 0F) {
        size += 1 + 4;
      }
      if (Id != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Id);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CharityCase other) {
      if (other == null) {
        return;
      }
      if (other.CaseName.Length != 0) {
        CaseName = other.CaseName;
      }
      if (other.TotalAmount != 0F) {
        TotalAmount = other.TotalAmount;
      }
      if (other.Id != 0L) {
        Id = other.Id;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            CaseName = input.ReadString();
            break;
          }
          case 21: {
            TotalAmount = input.ReadFloat();
            break;
          }
          case 24: {
            Id = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            CaseName = input.ReadString();
            break;
          }
          case 21: {
            TotalAmount = input.ReadFloat();
            break;
          }
          case 24: {
            Id = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class TeledonRequest : pb::IMessage<TeledonRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TeledonRequest> _parser = new pb::MessageParser<TeledonRequest>(() => new TeledonRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TeledonRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Proto.ProtoBuffProtocol.TeledonProtocolV3Reflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TeledonRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TeledonRequest(TeledonRequest other) : this() {
      type_ = other.type_;
      switch (other.PayloadCase) {
        case PayloadOneofCase.User:
          User = other.User.Clone();
          break;
        case PayloadOneofCase.SearchName:
          SearchName = other.SearchName;
          break;
        case PayloadOneofCase.Donation:
          Donation = other.Donation.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TeledonRequest Clone() {
      return new TeledonRequest(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private global::Proto.ProtoBuffProtocol.TeledonRequest.Types.Type type_ = global::Proto.ProtoBuffProtocol.TeledonRequest.Types.Type.Unknown;
    /// <summary>
    /// Identifies which request is filled in.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Proto.ProtoBuffProtocol.TeledonRequest.Types.Type Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "user" field.</summary>
    public const int UserFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Proto.ProtoBuffProtocol.Volunteer User {
      get { return payloadCase_ == PayloadOneofCase.User ? (global::Proto.ProtoBuffProtocol.Volunteer) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.User;
      }
    }

    /// <summary>Field number for the "searchName" field.</summary>
    public const int SearchNameFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string SearchName {
      get { return payloadCase_ == PayloadOneofCase.SearchName ? (string) payload_ : ""; }
      set {
        payload_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        payloadCase_ = PayloadOneofCase.SearchName;
      }
    }

    /// <summary>Field number for the "donation" field.</summary>
    public const int DonationFieldNumber = 5;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Proto.ProtoBuffProtocol.Donation Donation {
      get { return payloadCase_ == PayloadOneofCase.Donation ? (global::Proto.ProtoBuffProtocol.Donation) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.Donation;
      }
    }

    private object payload_;
    /// <summary>Enum of possible cases for the "payload" oneof.</summary>
    public enum PayloadOneofCase {
      None = 0,
      User = 2,
      SearchName = 3,
      Donation = 5,
    }
    private PayloadOneofCase payloadCase_ = PayloadOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PayloadOneofCase PayloadCase {
      get { return payloadCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPayload() {
      payloadCase_ = PayloadOneofCase.None;
      payload_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TeledonRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TeledonRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if (!object.Equals(User, other.User)) return false;
      if (SearchName != other.SearchName) return false;
      if (!object.Equals(Donation, other.Donation)) return false;
      if (PayloadCase != other.PayloadCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Type != global::Proto.ProtoBuffProtocol.TeledonRequest.Types.Type.Unknown) hash ^= Type.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.User) hash ^= User.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.SearchName) hash ^= SearchName.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.Donation) hash ^= Donation.GetHashCode();
      hash ^= (int) payloadCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Type != global::Proto.ProtoBuffProtocol.TeledonRequest.Types.Type.Unknown) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (payloadCase_ == PayloadOneofCase.User) {
        output.WriteRawTag(18);
        output.WriteMessage(User);
      }
      if (payloadCase_ == PayloadOneofCase.SearchName) {
        output.WriteRawTag(26);
        output.WriteString(SearchName);
      }
      if (payloadCase_ == PayloadOneofCase.Donation) {
        output.WriteRawTag(42);
        output.WriteMessage(Donation);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Type != global::Proto.ProtoBuffProtocol.TeledonRequest.Types.Type.Unknown) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (payloadCase_ == PayloadOneofCase.User) {
        output.WriteRawTag(18);
        output.WriteMessage(User);
      }
      if (payloadCase_ == PayloadOneofCase.SearchName) {
        output.WriteRawTag(26);
        output.WriteString(SearchName);
      }
      if (payloadCase_ == PayloadOneofCase.Donation) {
        output.WriteRawTag(42);
        output.WriteMessage(Donation);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Type != global::Proto.ProtoBuffProtocol.TeledonRequest.Types.Type.Unknown) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (payloadCase_ == PayloadOneofCase.User) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(User);
      }
      if (payloadCase_ == PayloadOneofCase.SearchName) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SearchName);
      }
      if (payloadCase_ == PayloadOneofCase.Donation) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Donation);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TeledonRequest other) {
      if (other == null) {
        return;
      }
      if (other.Type != global::Proto.ProtoBuffProtocol.TeledonRequest.Types.Type.Unknown) {
        Type = other.Type;
      }
      switch (other.PayloadCase) {
        case PayloadOneofCase.User:
          if (User == null) {
            User = new global::Proto.ProtoBuffProtocol.Volunteer();
          }
          User.MergeFrom(other.User);
          break;
        case PayloadOneofCase.SearchName:
          SearchName = other.SearchName;
          break;
        case PayloadOneofCase.Donation:
          if (Donation == null) {
            Donation = new global::Proto.ProtoBuffProtocol.Donation();
          }
          Donation.MergeFrom(other.Donation);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Type = (global::Proto.ProtoBuffProtocol.TeledonRequest.Types.Type) input.ReadEnum();
            break;
          }
          case 18: {
            global::Proto.ProtoBuffProtocol.Volunteer subBuilder = new global::Proto.ProtoBuffProtocol.Volunteer();
            if (payloadCase_ == PayloadOneofCase.User) {
              subBuilder.MergeFrom(User);
            }
            input.ReadMessage(subBuilder);
            User = subBuilder;
            break;
          }
          case 26: {
            SearchName = input.ReadString();
            break;
          }
          case 42: {
            global::Proto.ProtoBuffProtocol.Donation subBuilder = new global::Proto.ProtoBuffProtocol.Donation();
            if (payloadCase_ == PayloadOneofCase.Donation) {
              subBuilder.MergeFrom(Donation);
            }
            input.ReadMessage(subBuilder);
            Donation = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Type = (global::Proto.ProtoBuffProtocol.TeledonRequest.Types.Type) input.ReadEnum();
            break;
          }
          case 18: {
            global::Proto.ProtoBuffProtocol.Volunteer subBuilder = new global::Proto.ProtoBuffProtocol.Volunteer();
            if (payloadCase_ == PayloadOneofCase.User) {
              subBuilder.MergeFrom(User);
            }
            input.ReadMessage(subBuilder);
            User = subBuilder;
            break;
          }
          case 26: {
            SearchName = input.ReadString();
            break;
          }
          case 42: {
            global::Proto.ProtoBuffProtocol.Donation subBuilder = new global::Proto.ProtoBuffProtocol.Donation();
            if (payloadCase_ == PayloadOneofCase.Donation) {
              subBuilder.MergeFrom(Donation);
            }
            input.ReadMessage(subBuilder);
            Donation = subBuilder;
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the TeledonRequest message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum Type {
        [pbr::OriginalName("Unknown")] Unknown = 0,
        [pbr::OriginalName("Login")] Login = 1,
        [pbr::OriginalName("Logout")] Logout = 2,
        [pbr::OriginalName("GetDonations")] GetDonations = 3,
        [pbr::OriginalName("GetCharityCases")] GetCharityCases = 4,
        [pbr::OriginalName("AddDonation")] AddDonation = 5,
      }

    }
    #endregion

  }

  public sealed partial class TeledonResponse : pb::IMessage<TeledonResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TeledonResponse> _parser = new pb::MessageParser<TeledonResponse>(() => new TeledonResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TeledonResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Proto.ProtoBuffProtocol.TeledonProtocolV3Reflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TeledonResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TeledonResponse(TeledonResponse other) : this() {
      type_ = other.type_;
      error_ = other.error_;
      donations_ = other.donations_.Clone();
      cases_ = other.cases_.Clone();
      cases2_ = other.cases2_.Clone();
      donation_ = other.donation_ != null ? other.donation_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TeledonResponse Clone() {
      return new TeledonResponse(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private global::Proto.ProtoBuffProtocol.TeledonResponse.Types.Type type_ = global::Proto.ProtoBuffProtocol.TeledonResponse.Types.Type.Unknown;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Proto.ProtoBuffProtocol.TeledonResponse.Types.Type Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "error" field.</summary>
    public const int ErrorFieldNumber = 2;
    private string error_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Error {
      get { return error_; }
      set {
        error_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "donations" field.</summary>
    public const int DonationsFieldNumber = 3;
    private static readonly pb::FieldCodec<global::Proto.ProtoBuffProtocol.Donation> _repeated_donations_codec
        = pb::FieldCodec.ForMessage(26, global::Proto.ProtoBuffProtocol.Donation.Parser);
    private readonly pbc::RepeatedField<global::Proto.ProtoBuffProtocol.Donation> donations_ = new pbc::RepeatedField<global::Proto.ProtoBuffProtocol.Donation>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Proto.ProtoBuffProtocol.Donation> Donations {
      get { return donations_; }
    }

    /// <summary>Field number for the "cases" field.</summary>
    public const int CasesFieldNumber = 4;
    private static readonly pb::FieldCodec<global::Proto.ProtoBuffProtocol.CharityCase> _repeated_cases_codec
        = pb::FieldCodec.ForMessage(34, global::Proto.ProtoBuffProtocol.CharityCase.Parser);
    private readonly pbc::RepeatedField<global::Proto.ProtoBuffProtocol.CharityCase> cases_ = new pbc::RepeatedField<global::Proto.ProtoBuffProtocol.CharityCase>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Proto.ProtoBuffProtocol.CharityCase> Cases {
      get { return cases_; }
    }

    /// <summary>Field number for the "cases2" field.</summary>
    public const int Cases2FieldNumber = 6;
    private static readonly pb::FieldCodec<global::Proto.ProtoBuffProtocol.CharityCase> _repeated_cases2_codec
        = pb::FieldCodec.ForMessage(50, global::Proto.ProtoBuffProtocol.CharityCase.Parser);
    private readonly pbc::RepeatedField<global::Proto.ProtoBuffProtocol.CharityCase> cases2_ = new pbc::RepeatedField<global::Proto.ProtoBuffProtocol.CharityCase>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Proto.ProtoBuffProtocol.CharityCase> Cases2 {
      get { return cases2_; }
    }

    /// <summary>Field number for the "donation" field.</summary>
    public const int DonationFieldNumber = 5;
    private global::Proto.ProtoBuffProtocol.Donation donation_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Proto.ProtoBuffProtocol.Donation Donation {
      get { return donation_; }
      set {
        donation_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TeledonResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TeledonResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if (Error != other.Error) return false;
      if(!donations_.Equals(other.donations_)) return false;
      if(!cases_.Equals(other.cases_)) return false;
      if(!cases2_.Equals(other.cases2_)) return false;
      if (!object.Equals(Donation, other.Donation)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Type != global::Proto.ProtoBuffProtocol.TeledonResponse.Types.Type.Unknown) hash ^= Type.GetHashCode();
      if (Error.Length != 0) hash ^= Error.GetHashCode();
      hash ^= donations_.GetHashCode();
      hash ^= cases_.GetHashCode();
      hash ^= cases2_.GetHashCode();
      if (donation_ != null) hash ^= Donation.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Type != global::Proto.ProtoBuffProtocol.TeledonResponse.Types.Type.Unknown) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (Error.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Error);
      }
      donations_.WriteTo(output, _repeated_donations_codec);
      cases_.WriteTo(output, _repeated_cases_codec);
      if (donation_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Donation);
      }
      cases2_.WriteTo(output, _repeated_cases2_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Type != global::Proto.ProtoBuffProtocol.TeledonResponse.Types.Type.Unknown) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (Error.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Error);
      }
      donations_.WriteTo(ref output, _repeated_donations_codec);
      cases_.WriteTo(ref output, _repeated_cases_codec);
      if (donation_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Donation);
      }
      cases2_.WriteTo(ref output, _repeated_cases2_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Type != global::Proto.ProtoBuffProtocol.TeledonResponse.Types.Type.Unknown) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (Error.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Error);
      }
      size += donations_.CalculateSize(_repeated_donations_codec);
      size += cases_.CalculateSize(_repeated_cases_codec);
      size += cases2_.CalculateSize(_repeated_cases2_codec);
      if (donation_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Donation);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TeledonResponse other) {
      if (other == null) {
        return;
      }
      if (other.Type != global::Proto.ProtoBuffProtocol.TeledonResponse.Types.Type.Unknown) {
        Type = other.Type;
      }
      if (other.Error.Length != 0) {
        Error = other.Error;
      }
      donations_.Add(other.donations_);
      cases_.Add(other.cases_);
      cases2_.Add(other.cases2_);
      if (other.donation_ != null) {
        if (donation_ == null) {
          Donation = new global::Proto.ProtoBuffProtocol.Donation();
        }
        Donation.MergeFrom(other.Donation);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Type = (global::Proto.ProtoBuffProtocol.TeledonResponse.Types.Type) input.ReadEnum();
            break;
          }
          case 18: {
            Error = input.ReadString();
            break;
          }
          case 26: {
            donations_.AddEntriesFrom(input, _repeated_donations_codec);
            break;
          }
          case 34: {
            cases_.AddEntriesFrom(input, _repeated_cases_codec);
            break;
          }
          case 42: {
            if (donation_ == null) {
              Donation = new global::Proto.ProtoBuffProtocol.Donation();
            }
            input.ReadMessage(Donation);
            break;
          }
          case 50: {
            cases2_.AddEntriesFrom(input, _repeated_cases2_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Type = (global::Proto.ProtoBuffProtocol.TeledonResponse.Types.Type) input.ReadEnum();
            break;
          }
          case 18: {
            Error = input.ReadString();
            break;
          }
          case 26: {
            donations_.AddEntriesFrom(ref input, _repeated_donations_codec);
            break;
          }
          case 34: {
            cases_.AddEntriesFrom(ref input, _repeated_cases_codec);
            break;
          }
          case 42: {
            if (donation_ == null) {
              Donation = new global::Proto.ProtoBuffProtocol.Donation();
            }
            input.ReadMessage(Donation);
            break;
          }
          case 50: {
            cases2_.AddEntriesFrom(ref input, _repeated_cases2_codec);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the TeledonResponse message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum Type {
        [pbr::OriginalName("Unknown")] Unknown = 0,
        [pbr::OriginalName("Ok")] Ok = 1,
        [pbr::OriginalName("Error")] Error = 2,
        [pbr::OriginalName("GetDonations")] GetDonations = 3,
        [pbr::OriginalName("GetCharityCases")] GetCharityCases = 4,
        [pbr::OriginalName("NewDonation")] NewDonation = 5,
        [pbr::OriginalName("UpdateCases")] UpdateCases = 6,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
